let itemarray = [
    {
        image: 1,
        rating: 4.5,
        review: 17999,
        companyname: 'Carton London',
        itemname: 'Rhodium-plated CZ,floral studs',
        discountedprice: 606,
        originalprice: 1045,
        discountpercentage: 45,
    },
    {
        image: 2,
        rating: 4.3,
        review: 24,
        companyname: 'CUKOO',
        itemname: 'Women Padded Halter Neck...',
        discountedprice: 1507,
        originalprice: 2599,
        discountpercentage: 45,
    },
    {
        image: 3,
        rating: 4.1,
        review: 249,
        companyname: 'NUEVOSDAMAS',
        itemname: 'Women Red & White Printed A..',
        discountedprice: 495,
        originalprice: 1599,
        discountpercentage: 69,
    },
    {
        image: 4,
        rating: 5.0,
        review: 10,
        companyname: 'ADIDAS',
        itemname: 'Indian Cricket ODI Jersey',
        discountedprice: 999,
        originalprice: 999,
        discountpercentage: 0,
    },
    {
        image: 5,
        rating: 4.2,
        review: 3500,
        companyname: 'Roadster',
        itemname: 'Pure Cotton T-shirt',
        discountedprice: 489,
        originalprice: 1399,
        discountpercentage:65,
    },
    {
        image: 6,
        rating: 0.0,
        review: 0,
        companyname: 'Nike',
        itemname: 'Men ReactX Running Shoes',
        discountedprice: 14995,
        originalprice: 14995,
        discountpercentage:0,
    },
    {
        image: 7,
        rating: 4.2,
        review: 388,
        companyname: 'The Indian Garage Co',
        itemname: 'Men Slim Fit Regular Shorts',
        discountedprice: 639,
        originalprice: 1599,
        discountpercentage: 60,
    },
    {
        image: 8,
        rating: 4.2,
        review: 5200,
        companyname: 'NIVEA',
        itemname: 'Men Fresh Deodrant 150ml',
        discountedprice:142,
        originalprice: 285,
        discountpercentage: 50,
    },
    {
        image: 9,
        rating: 4.5,
        review: 1000,
        companyname: 'FAST-TRACK',
        itemname: 'Analog wrist watch clasical...',
        discountedprice: 1000,
        originalprice: 1500,
        discountpercentage: 35,
    },
    {
        image: 10,
        rating: 4.0,
        review: 2000,
        companyname: 'RAYMOND',
        itemname: 'Premium Shirts From the brand...',
        discountedprice: 606,
        originalprice: 1045,
        discountpercentage: 45,
    },
];